// module.exports = {
//     "TUMBLR_CONSUMER_KEY":"TIM0Cp3kgs8SD0gBjYMGzQathfPBDU1GGlMDKe0jWGBScvdvt5",
//     "TUMBLR_CONSUMER_SKEY":"ZluUHfZXGMtTKCbfOX038rw53hLsMfERbiPTdoMokoPQ8mIgMW",
//     "TUMBLR_ACCESS_TOKEN":"2Dv30U4DMMGaFE0NjIHSOtARQLO49FaABwsWJW90Vzf9FBOJU0",
//     "TUMBLR_ACCESS_STOKEN":"KsRl5RI4nPyafumxNiVYEY4YoBcSnXrFNu14DnE7ouGiNpBoXa"
// }

module.exports = Object.freeze({
    TUMBLR_CONSUMER_KEY: "TIM0Cp3kgs8SD0gBjYMGzQathfPBDU1GGlMDKe0jWGBScvdvt5",
    TUMBLR_CONSUMER_SKEY: "ZluUHfZXGMtTKCbfOX038rw53hLsMfERbiPTdoMokoPQ8mIgMW",
    TUMBLR_ACCESS_TOKEN: "DAjfBHoIvDDjKjoehck8WPxjVagO02wxTN3uDUIRdogg2lamVI",
    TUMBLR_ACCESS_STOKEN: "7GE4wWY3Oo6jlMkWhxbac4Xo3X3d8c3DuOOrDS5UedHjbiJDQu"
});